# Generated by Django 5.0.7 on 2024-08-07 13:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(64),
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Красный"),
                            ("orange", "Оранжевый"),
                            ("amber", "Янтарный"),
                            ("yellow", "Желтый"),
                            ("lime", "Лайм"),
                            ("green", "Зеленый"),
                            ("emerald", "Изумрудный"),
                            ("teal", "Тиловый"),
                            ("cyan", "Голубой"),
                            ("sky", "Небесно-голубой"),
                            ("blue", "Синий"),
                            ("indigo", "Индиго"),
                            ("violet", "Фиолетовый"),
                            ("purple", "Пурпурный"),
                            ("fuchsia", "Фуксия"),
                            ("pink", "Розовый"),
                            ("rose", "Розовый"),
                            ("gray", "Серый"),
                            ("white", "Белый"),
                            ("black", "Черный"),
                            ("primary", "Основной"),
                        ],
                        default="gray",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(64),
                        ],
                        verbose_name="Название",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Окружение",
                "verbose_name_plural": "Окружения",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        max_length=256,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(256),
                        ],
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(2048)],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="tickets", to="core.tag", verbose_name="Теги"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.workspace",
                        verbose_name="Окружение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тикет",
                "verbose_name_plural": "Тикеты",
                "ordering": ["-created_at"],
                "get_latest_by": "-created_at",
            },
        ),
    ]
